<a href="https://colab.research.google.com/github/vaas-umputer/naan_mudhalvan_ai_3562/blob/main/AI_Phase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("USA_Housing.csv")

In [3]:
data.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386

In [4]:
# Data Preprocessing
from sklearn.model_selection import train_test_split

# Load your data into a DataFrame (replace 'data' with your actual DataFrame name)
# data = pd.read_csv("your_data.csv")

# Separate the target variable from the features
X = data.drop("Price", axis=1)
y = data["Price"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature Engineering (if needed)
# Example: Create new feature "Bedrooms per Room"
X_train["Bedrooms per Room"] = X_train["Avg. Area Number of Bedrooms"] / X_train["Avg. Area Number of Rooms"]
X_test["Bedrooms per Room"] = X_test["Avg. Area Number of Bedrooms"] / X_test["Avg. Area Number of Rooms"]

# Handle Missing Values (if needed)
# Example: Replace missing values with the mean
X_train.fillna(X_train.mean(numeric_only=True), inplace=True)
X_test.fillna(X_test.mean(numeric_only=True), inplace=True)

# Data Cleaning (if needed)
# Example: Remove duplicate records
#X_train.drop_duplicates(inplace=True)
#X_test.drop_duplicates(inplace=True)

# Handle Missing Values (if needed)
# Example: Replace missing values with the mean
X_train.fillna(X_train.mean(numeric_only=True), inplace=True)
X_test.fillna(X_test.mean(numeric_only=True), inplace=True)

# Feature Scaling (if needed)
# Example: Standardize numerical features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numerical_features = ["Avg. Area Income", "Avg. Area House Age", "Avg. Area Number of Rooms", "Avg. Area Number of Bedrooms", "Area Population"]
X_train[numerical_features] = scaler.fit_transform(X_train[numerical_features])
X_test[numerical_features] = scaler.transform(X_test[numerical_features])

In [5]:
X_train['Bedrooms per Room'] = X_train['Bedrooms per Room'].abs()

In [6]:
print(X_train)

      Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
4227         -0.190492            -0.128177                  -0.131606
4676         -1.388764             0.430804                   0.800285
800          -0.350124             0.466808                   1.703751
3671         -0.139098             0.114079                   0.229733
4193          0.622225             2.208957                   0.435972
...                ...                  ...                        ...
4426          0.713611             0.400843                  -1.622964
466          -1.111923             0.991153                   0.517240
3092         -0.223351             0.538092                  -0.364897
3772         -0.924171             1.430774                   2.268463
860          -0.693573            -0.077623                   0.892196

      Avg. Area Number of Bedrooms  Area Population  \
4227                      0.120386        -0.827618
4676                     -0.556489         1.158299
800                       0.030680        -0.319043
3671                     -0.760367        -0.893752
4193                     -0.458628         0.131301
...                            ...              ...
4426                     -1.274139        -0.595456
466                      -0.491248         0.724265
3092                     -0.686971         0.119089
3772                      0.275333         1.390184
860                       1.678013        -0.006819

                                                Address  Bedrooms per Room
4227  2288 Gary Square Apt. 812\nWest Jose, PR 78536...           0.603158
4676                         USS Williams\nFPO AE 65283           0.423742
800               Unit 2193 Box 7909\nDPO AA 47323-2101           0.462093
3671  052 Thomas Square Apt. 034\nWrightmouth, OR 04272           0.422908
4193  879 Martha Route Suite 031\nNew Nichole, VI 60708           0.460910
...                                                 ...                ...
4426  8456 Rodgers Burg Apt. 215\nSouth Michelle, NM...           0.452995
466     8584 Darrell Groves\nBennettberg, SD 72404-6826           0.450540
3092        8367 Manuel Road\nNathanfort, AS 36077-1481           0.474904
3772                   Unit 7385 Box 9302\nDPO AP 21450           0.466047
860      06275 Ross Mills Suite 054\nLisastad, DC 67330           0.766447

[4000 rows x 7 columns]